name: Java

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: ALLURE_JOB_RUN_ID - service parameter (leave blank)
        required: false
      ALLURE_USERNAME:
        description: ALLURE_USERNAME - service parameter (leave blank)
        required: false

env:
  ALLURE_ENDPOINT: https://sandbox.testops.cloud/
  ALLURE_PROJECT_ID: 35
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_TESTPLAN_PATH: "./testplan.json"
  ALLURE_RESULTS: "build/allure-results"


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
                 
      - name: Install allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          ALLURE_ENDPOINT: https://sandbox.testops.cloud/
          ALLURE_PROJECT_ID: ${{ github.event.inputs.ALLURE_PROJECT_ID}}
          ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
          
      - name: Run tests
        run: |
          chmod +x ./gradlew 
          allurectl watch -- ./gradlew clean test
        env:
          BRANCH: ${{ github.ref_name }}
          BROWSER: 'Chrome'
          ENDPOINT: 'sandbox.testops.cloud'
          OS: 'macOS'
          VERSION: '5.1.2'		  
          ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
          ALLURE_TESTPLAN_PATH: "./testplan.json"
          ALLURE_RESULTS: "build/allure-results"
